/* User Constants */
export const GET_USER_NAME_SUCCESS = "GET_USER_NAME_SUCCESS";
export const GET_USER_ALIAS_SUCCESS = "GET_USER_ALIAS_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_PREFERNCES_SUCCESS = "UPDATE_USER_PREFERNCES_SUCCESS";
export const UPDATE_USER_CHECKED_SUCCESS = "UPDATE_USER_CHECKED_SUCCESS";
export const UPDATE_USER_TRANSACTION_SUCCESS =
  "UPDATE_USER_TRANSACTION_SUCCESS";
export const GET_USER_TRANSACTION_SUCCESS = "UPDATE_USER_TRANSACTION_SUCCESS";

/* Test Constants */
export const UPDATE_TEST_SUCCESS = "UPDATE_TEST_SUCCESS";

/* Auth Reducers */
export const UPDATE_AUTH_SUCCESS = "UPDATE_AUTH_SUCCESS";
export const GET_AUTH_SUCCESS = "GET_AUTH_SUCCESS";
